# Generated by Django 3.2.5 on 2021-08-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoc', '0006_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, height_field='300px', null=True, upload_to='', width_field='100px'),
        ),
    ]
