# Generated by Django 3.2.5 on 2021-08-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoc', '0008_alter_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='commentaire',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='headline',
            new_name='titre',
        ),
    ]
