# Generated by Django 3.2.5 on 2021-08-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoc', '0011_userfollows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='commentaire',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
